name: ongkos_kirim
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  dropdown_search: ^0.6.3
  get: 4.6.5
  flutter:
    sdk: flutter

dev_dependencies:
  # flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
flutter:
  uses-material-design: true
